### ISSUE TITLE
Generating an empty changelog

### ISSUE THREAD

**Issue by JustinBeckwith** [GoogleCloudPlatform/releasetool#21] opened 2018-08-06 17:49 UTC
I'm running `releasetool start` against master in nodejs-common:
https://github.com/googleapis/nodejs-common/

It's popping up an empty change log, even though there are many changes.  

```
nodejs-common (master) $ releasetool start
Which language (python, python-tool, nodejs)?: nodejs
o/ Hey, beckwith, let's release some stuff!
> Determining basic context.
GitHub Repo: JustinBeckwith/nodejs-common
> Figuring out the package name.
Looks like we're releasing nodejs-common.
> Figuring out what the last release was.
The last release was 0.20.3.
> Gathering changes since 0.20.3
Cool, 1 changes found.
> Opening your editor to finalize release notes.
```

And the changelog it generates:

```
- 

### Implementation Changes

### New Features

### Dependencies

### Documentation

### Internal / Testing Changes
```

The actual changes:

```
3894cf4 chore: update renovate config (#202)
beda6c2 fix: make ServiceObject#id protected to allow subclass access (#200)
3004afa refactor: remove circular imports (#201)
3f764bf fix: special JSON.stringify for for strictEqual test (#199)
dbddd19 chore: assert.deelEqual => assert.deepStrictEqual (#196)
ba0f858 chore: move mocha options to mocha.opts (#195)
be06c73 chore(deps): update dependency gts to ^0.8.0 (#192)
94afcdf chore: cut out code split into other modules (#194)
46c910a Update config.yml (#191)
3d74038 fix: drop support for node.js 4.x and 9.x (#190)
```

**Comment by theacodes** [comment] 2018-08-10 19:43
Duplicate of #8.

**Closed by theacodes** 2018-08-10 19:43 UTC
Labels: priority: p1, type: bug

**Comment by theacodes** [comment] 2018-08-10 19:48
Err, #9, but related to #8.
